name: stak-notebooks
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - numpy
  - scipy
  - astropy
  - astroquery
  - numpydoc
  - nbconvert>=5.0.0
  - sphinx>=1.5
  - sphinx_rtd_theme==0.3.1
  - stsci_rtd_theme
  - ipython

